#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SampleMapsApp.Resource", IsApplication=true)]

namespace SampleMapsApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GoogleMapsUtils.Android.Resource.Attribute.ambientEnabled = global::SampleMapsApp.Resource.Attribute.ambientEnabled;
			global::GoogleMapsUtils.Android.Resource.Attribute.buttonSize = global::SampleMapsApp.Resource.Attribute.buttonSize;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraBearing = global::SampleMapsApp.Resource.Attribute.cameraBearing;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraMaxZoomPreference = global::SampleMapsApp.Resource.Attribute.cameraMaxZoomPreference;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraMinZoomPreference = global::SampleMapsApp.Resource.Attribute.cameraMinZoomPreference;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraTargetLat = global::SampleMapsApp.Resource.Attribute.cameraTargetLat;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraTargetLng = global::SampleMapsApp.Resource.Attribute.cameraTargetLng;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraTilt = global::SampleMapsApp.Resource.Attribute.cameraTilt;
			global::GoogleMapsUtils.Android.Resource.Attribute.cameraZoom = global::SampleMapsApp.Resource.Attribute.cameraZoom;
			global::GoogleMapsUtils.Android.Resource.Attribute.circleCrop = global::SampleMapsApp.Resource.Attribute.circleCrop;
			global::GoogleMapsUtils.Android.Resource.Attribute.colorScheme = global::SampleMapsApp.Resource.Attribute.colorScheme;
			global::GoogleMapsUtils.Android.Resource.Attribute.imageAspectRatio = global::SampleMapsApp.Resource.Attribute.imageAspectRatio;
			global::GoogleMapsUtils.Android.Resource.Attribute.imageAspectRatioAdjust = global::SampleMapsApp.Resource.Attribute.imageAspectRatioAdjust;
			global::GoogleMapsUtils.Android.Resource.Attribute.latLngBoundsNorthEastLatitude = global::SampleMapsApp.Resource.Attribute.latLngBoundsNorthEastLatitude;
			global::GoogleMapsUtils.Android.Resource.Attribute.latLngBoundsNorthEastLongitude = global::SampleMapsApp.Resource.Attribute.latLngBoundsNorthEastLongitude;
			global::GoogleMapsUtils.Android.Resource.Attribute.latLngBoundsSouthWestLatitude = global::SampleMapsApp.Resource.Attribute.latLngBoundsSouthWestLatitude;
			global::GoogleMapsUtils.Android.Resource.Attribute.latLngBoundsSouthWestLongitude = global::SampleMapsApp.Resource.Attribute.latLngBoundsSouthWestLongitude;
			global::GoogleMapsUtils.Android.Resource.Attribute.liteMode = global::SampleMapsApp.Resource.Attribute.liteMode;
			global::GoogleMapsUtils.Android.Resource.Attribute.mapType = global::SampleMapsApp.Resource.Attribute.mapType;
			global::GoogleMapsUtils.Android.Resource.Attribute.scopeUris = global::SampleMapsApp.Resource.Attribute.scopeUris;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiCompass = global::SampleMapsApp.Resource.Attribute.uiCompass;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiMapToolbar = global::SampleMapsApp.Resource.Attribute.uiMapToolbar;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiRotateGestures = global::SampleMapsApp.Resource.Attribute.uiRotateGestures;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiScrollGestures = global::SampleMapsApp.Resource.Attribute.uiScrollGestures;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiTiltGestures = global::SampleMapsApp.Resource.Attribute.uiTiltGestures;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiZoomControls = global::SampleMapsApp.Resource.Attribute.uiZoomControls;
			global::GoogleMapsUtils.Android.Resource.Attribute.uiZoomGestures = global::SampleMapsApp.Resource.Attribute.uiZoomGestures;
			global::GoogleMapsUtils.Android.Resource.Attribute.useViewLifecycle = global::SampleMapsApp.Resource.Attribute.useViewLifecycle;
			global::GoogleMapsUtils.Android.Resource.Attribute.zOrderOnTop = global::SampleMapsApp.Resource.Attribute.zOrderOnTop;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_dark = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_dark;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_dark_default = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_dark_default;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_dark_disabled = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_dark_focused = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_dark_pressed = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_light = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_light;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_light_default = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_light_default;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_light_disabled = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_light_focused = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_light_focused;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_text_light_pressed = global::SampleMapsApp.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::GoogleMapsUtils.Android.Resource.Color.common_google_signin_btn_tint = global::SampleMapsApp.Resource.Color.common_google_signin_btn_tint;
			global::GoogleMapsUtils.Android.Resource.Drawable.amu_bubble_mask = global::SampleMapsApp.Resource.Drawable.amu_bubble_mask;
			global::GoogleMapsUtils.Android.Resource.Drawable.amu_bubble_shadow = global::SampleMapsApp.Resource.Drawable.amu_bubble_shadow;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_full_open_on_phone = global::SampleMapsApp.Resource.Drawable.common_full_open_on_phone;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_dark = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_dark_normal_background;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_disabled = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_disabled;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_light = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_light;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_icon_light_normal_background = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_icon_light_normal_background;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_dark = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_dark;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_dark_normal_background = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_dark_normal_background;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_disabled = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_disabled;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_light = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_light;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_light_focused = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_light_normal = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::GoogleMapsUtils.Android.Resource.Drawable.common_google_signin_btn_text_light_normal_background = global::SampleMapsApp.Resource.Drawable.common_google_signin_btn_text_light_normal_background;
			global::GoogleMapsUtils.Android.Resource.Drawable.googleg_disabled_color_18 = global::SampleMapsApp.Resource.Drawable.googleg_disabled_color_18;
			global::GoogleMapsUtils.Android.Resource.Drawable.googleg_standard_color_18 = global::SampleMapsApp.Resource.Drawable.googleg_standard_color_18;
			global::GoogleMapsUtils.Android.Resource.Id.adjust_height = global::SampleMapsApp.Resource.Id.adjust_height;
			global::GoogleMapsUtils.Android.Resource.Id.adjust_width = global::SampleMapsApp.Resource.Id.adjust_width;
			global::GoogleMapsUtils.Android.Resource.Id.amu_text = global::SampleMapsApp.Resource.Id.amu_text;
			global::GoogleMapsUtils.Android.Resource.Id.auto = global::SampleMapsApp.Resource.Id.auto;
			global::GoogleMapsUtils.Android.Resource.Id.dark = global::SampleMapsApp.Resource.Id.dark;
			global::GoogleMapsUtils.Android.Resource.Id.hybrid = global::SampleMapsApp.Resource.Id.hybrid;
			global::GoogleMapsUtils.Android.Resource.Id.icon_only = global::SampleMapsApp.Resource.Id.icon_only;
			global::GoogleMapsUtils.Android.Resource.Id.light = global::SampleMapsApp.Resource.Id.light;
			global::GoogleMapsUtils.Android.Resource.Id.none = global::SampleMapsApp.Resource.Id.none;
			global::GoogleMapsUtils.Android.Resource.Id.normal = global::SampleMapsApp.Resource.Id.normal;
			global::GoogleMapsUtils.Android.Resource.Id.satellite = global::SampleMapsApp.Resource.Id.satellite;
			global::GoogleMapsUtils.Android.Resource.Id.standard = global::SampleMapsApp.Resource.Id.standard;
			global::GoogleMapsUtils.Android.Resource.Id.terrain = global::SampleMapsApp.Resource.Id.terrain;
			global::GoogleMapsUtils.Android.Resource.Id.webview = global::SampleMapsApp.Resource.Id.webview;
			global::GoogleMapsUtils.Android.Resource.Id.wide = global::SampleMapsApp.Resource.Id.wide;
			global::GoogleMapsUtils.Android.Resource.Id.window = global::SampleMapsApp.Resource.Id.window;
			global::GoogleMapsUtils.Android.Resource.Integer.google_play_services_version = global::SampleMapsApp.Resource.Integer.google_play_services_version;
			global::GoogleMapsUtils.Android.Resource.Layout.amu_info_window = global::SampleMapsApp.Resource.Layout.amu_info_window;
			global::GoogleMapsUtils.Android.Resource.Layout.amu_text_bubble = global::SampleMapsApp.Resource.Layout.amu_text_bubble;
			global::GoogleMapsUtils.Android.Resource.Layout.amu_webview = global::SampleMapsApp.Resource.Layout.amu_webview;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_ballon_gx_prefix = global::SampleMapsApp.Resource.Raw.amu_ballon_gx_prefix;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_basic_folder = global::SampleMapsApp.Resource.Raw.amu_basic_folder;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_basic_placemark = global::SampleMapsApp.Resource.Raw.amu_basic_placemark;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_cdata = global::SampleMapsApp.Resource.Raw.amu_cdata;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_default_balloon = global::SampleMapsApp.Resource.Raw.amu_default_balloon;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_document_nest = global::SampleMapsApp.Resource.Raw.amu_document_nest;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_draw_order_ground_overlay = global::SampleMapsApp.Resource.Raw.amu_draw_order_ground_overlay;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_extended_data = global::SampleMapsApp.Resource.Raw.amu_extended_data;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_ground_overlay = global::SampleMapsApp.Resource.Raw.amu_ground_overlay;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_ground_overlay_color = global::SampleMapsApp.Resource.Raw.amu_ground_overlay_color;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_inline_style = global::SampleMapsApp.Resource.Raw.amu_inline_style;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_multigeometry_placemarks = global::SampleMapsApp.Resource.Raw.amu_multigeometry_placemarks;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_multiple_placemarks = global::SampleMapsApp.Resource.Raw.amu_multiple_placemarks;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_nested_folders = global::SampleMapsApp.Resource.Raw.amu_nested_folders;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_nested_multigeometry = global::SampleMapsApp.Resource.Raw.amu_nested_multigeometry;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_poly_style_boolean_alpha = global::SampleMapsApp.Resource.Raw.amu_poly_style_boolean_alpha;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_poly_style_boolean_numeric = global::SampleMapsApp.Resource.Raw.amu_poly_style_boolean_numeric;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_unknwown_folder = global::SampleMapsApp.Resource.Raw.amu_unknwown_folder;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_unsupported = global::SampleMapsApp.Resource.Raw.amu_unsupported;
			global::GoogleMapsUtils.Android.Resource.Raw.amu_visibility_ground_overlay = global::SampleMapsApp.Resource.Raw.amu_visibility_ground_overlay;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_enable_button = global::SampleMapsApp.Resource.String.common_google_play_services_enable_button;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_enable_text = global::SampleMapsApp.Resource.String.common_google_play_services_enable_text;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_enable_title = global::SampleMapsApp.Resource.String.common_google_play_services_enable_title;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_install_button = global::SampleMapsApp.Resource.String.common_google_play_services_install_button;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_install_text = global::SampleMapsApp.Resource.String.common_google_play_services_install_text;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_install_title = global::SampleMapsApp.Resource.String.common_google_play_services_install_title;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_notification_ticker = global::SampleMapsApp.Resource.String.common_google_play_services_notification_ticker;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_unknown_issue = global::SampleMapsApp.Resource.String.common_google_play_services_unknown_issue;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_unsupported_text = global::SampleMapsApp.Resource.String.common_google_play_services_unsupported_text;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_update_button = global::SampleMapsApp.Resource.String.common_google_play_services_update_button;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_update_text = global::SampleMapsApp.Resource.String.common_google_play_services_update_text;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_update_title = global::SampleMapsApp.Resource.String.common_google_play_services_update_title;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_updating_text = global::SampleMapsApp.Resource.String.common_google_play_services_updating_text;
			global::GoogleMapsUtils.Android.Resource.String.common_google_play_services_wear_update_text = global::SampleMapsApp.Resource.String.common_google_play_services_wear_update_text;
			global::GoogleMapsUtils.Android.Resource.String.common_open_on_phone = global::SampleMapsApp.Resource.String.common_open_on_phone;
			global::GoogleMapsUtils.Android.Resource.String.common_signin_button_text = global::SampleMapsApp.Resource.String.common_signin_button_text;
			global::GoogleMapsUtils.Android.Resource.String.common_signin_button_text_long = global::SampleMapsApp.Resource.String.common_signin_button_text_long;
			global::GoogleMapsUtils.Android.Resource.Style.amu_Bubble_TextAppearance_Dark = global::SampleMapsApp.Resource.Style.amu_Bubble_TextAppearance_Dark;
			global::GoogleMapsUtils.Android.Resource.Style.amu_Bubble_TextAppearance_Light = global::SampleMapsApp.Resource.Style.amu_Bubble_TextAppearance_Light;
			global::GoogleMapsUtils.Android.Resource.Style.amu_ClusterIcon_TextAppearance = global::SampleMapsApp.Resource.Style.amu_ClusterIcon_TextAppearance;
			global::GoogleMapsUtils.Android.Resource.Styleable.LoadingImageView = global::SampleMapsApp.Resource.Styleable.LoadingImageView;
			global::GoogleMapsUtils.Android.Resource.Styleable.LoadingImageView_circleCrop = global::SampleMapsApp.Resource.Styleable.LoadingImageView_circleCrop;
			global::GoogleMapsUtils.Android.Resource.Styleable.LoadingImageView_imageAspectRatio = global::SampleMapsApp.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::GoogleMapsUtils.Android.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::SampleMapsApp.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs = global::SampleMapsApp.Resource.Styleable.MapAttrs;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_ambientEnabled = global::SampleMapsApp.Resource.Styleable.MapAttrs_ambientEnabled;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraBearing = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraBearing;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraMaxZoomPreference = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraMaxZoomPreference;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraMinZoomPreference = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraMinZoomPreference;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraTargetLat = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraTargetLat;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraTargetLng = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraTargetLng;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraTilt = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraTilt;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_cameraZoom = global::SampleMapsApp.Resource.Styleable.MapAttrs_cameraZoom;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_latLngBoundsNorthEastLatitude = global::SampleMapsApp.Resource.Styleable.MapAttrs_latLngBoundsNorthEastLatitude;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_latLngBoundsNorthEastLongitude = global::SampleMapsApp.Resource.Styleable.MapAttrs_latLngBoundsNorthEastLongitude;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_latLngBoundsSouthWestLatitude = global::SampleMapsApp.Resource.Styleable.MapAttrs_latLngBoundsSouthWestLatitude;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_latLngBoundsSouthWestLongitude = global::SampleMapsApp.Resource.Styleable.MapAttrs_latLngBoundsSouthWestLongitude;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_liteMode = global::SampleMapsApp.Resource.Styleable.MapAttrs_liteMode;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_mapType = global::SampleMapsApp.Resource.Styleable.MapAttrs_mapType;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiCompass = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiCompass;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiMapToolbar = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiMapToolbar;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiRotateGestures = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiRotateGestures;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiScrollGestures = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiScrollGestures;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiTiltGestures = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiTiltGestures;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiZoomControls = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiZoomControls;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_uiZoomGestures = global::SampleMapsApp.Resource.Styleable.MapAttrs_uiZoomGestures;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_useViewLifecycle = global::SampleMapsApp.Resource.Styleable.MapAttrs_useViewLifecycle;
			global::GoogleMapsUtils.Android.Resource.Styleable.MapAttrs_zOrderOnTop = global::SampleMapsApp.Resource.Styleable.MapAttrs_zOrderOnTop;
			global::GoogleMapsUtils.Android.Resource.Styleable.SignInButton = global::SampleMapsApp.Resource.Styleable.SignInButton;
			global::GoogleMapsUtils.Android.Resource.Styleable.SignInButton_buttonSize = global::SampleMapsApp.Resource.Styleable.SignInButton_buttonSize;
			global::GoogleMapsUtils.Android.Resource.Styleable.SignInButton_colorScheme = global::SampleMapsApp.Resource.Styleable.SignInButton_colorScheme;
			global::GoogleMapsUtils.Android.Resource.Styleable.SignInButton_scopeUris = global::SampleMapsApp.Resource.Styleable.SignInButton_scopeUris;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int common_google_signin_btn_text_dark = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int common_google_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int common_google_signin_btn_text_dark_disabled = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int common_google_signin_btn_text_dark_focused = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_google_signin_btn_text_dark_pressed = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int common_google_signin_btn_text_light = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int common_google_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int common_google_signin_btn_text_light_disabled = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int common_google_signin_btn_text_light_focused = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_google_signin_btn_text_light_pressed = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_signin_btn_tint = 2131165194;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int amu_bubble_mask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int amu_bubble_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int googleg_disabled_color_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int googleg_standard_color_18 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int adjust_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int adjust_width = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int amu_text = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int auto = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int dark = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int hybrid = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int icon_only = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int light = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int list = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int map = 2131230737;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int normal = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int satellite = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int standard = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int terrain = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int webview = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int wide = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int window = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int amu_info_window = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int amu_text_bubble = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int amu_webview = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int map = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int amu_ballon_gx_prefix = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int amu_basic_folder = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int amu_basic_placemark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int amu_cdata = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int amu_default_balloon = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int amu_document_nest = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int amu_draw_order_ground_overlay = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int amu_extended_data = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int amu_ground_overlay = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int amu_ground_overlay_color = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int amu_inline_style = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int amu_multigeometry_placemarks = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int amu_multiple_placemarks = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int amu_nested_folders = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int amu_nested_multigeometry = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int amu_poly_style_boolean_alpha = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int amu_poly_style_boolean_numeric = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int amu_unknwown_folder = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int amu_unsupported = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int amu_visibility_ground_overlay = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int radar_search = 2130968596;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060011
			public const int app_name = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_enable_button = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_enable_text = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_title = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_install_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_notification_ticker = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_unsupported_text = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_button = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_update_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_title = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_wear_update_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_open_on_phone = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_signin_button_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_signin_button_text_long = 2131099664;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int amu_Bubble_TextAppearance_Dark = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int amu_Bubble_TextAppearance_Light = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int amu_ClusterIcon_TextAppearance = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
